class SpaceGrid:
    def __init__(self, width: int): ...

    # batch add
    def add_range(self, start: int, count: int, step: int, nameid: str | int): ...

    # batch remove
    def rem_range(self, start: int, count: int, step: int, nameid: str | int): ...

    def get(self, where: str | int, default = None): ...
