class Vector2:
    x: int
    y: int

    def __init__(self, x: int = ..., y: int = ...) -> None: ...
    def randomize(self, pos: "Vector2", bounds: "Bounds2") -> None: ...
    def copy(self) -> Vector2: ...
    def set(self, x: int, y: int) -> None: ...
    def __add__(self, other: Vector2): ...
    def __sub__(self, other: Vector2): ...
    def __repr__(self): ...

class Bounds2:
    @property
    def tl(self) -> Vector2: ...

    @property
    def br(self) -> Vector2: ...
    
    def __init__(self, tl: Vector2, br: Vector2) -> None: ...
    def contains_xy(self, x: int, y: int) -> bool: ...
    def __contains__(self, p: Vector2) -> bool: ...
    def __add__(self, v: Vector2) -> Bounds2: ...
    def shrink(self, x: int, y: int) -> Bounds2: ...
